<!doctype html>
<html>

  <head>
    <meta charset="utf-8">
    <title>MCF Mod List - Home</title>
	<link rel="stylesheet" type="text/css" href="resources/stylesheets/index.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="resources/stylesheets/nav.css" media="screen" />
  </head>
  
<body>

<center>
<img src="resources/images/mcfmodlist.png" width="670" height="122" alt="MCF-ModList"/><br/><br/>
<table class="nav">
	<thead>
		<th class="h">Home</th>
		<th class="nh"><a href="credits/">Credits</a></th>
		<th class="nh"><a href="latest/">Current List</a></th>
		<!--<th class="nh"><a href="installation/">Current List</a></th>-->
		<th class="nh"><a href="banners/">Banners</a></th>
	</thead>
</table>

<p class="n">The goal is to list all the mods for the current version of Minecraft. This doesn't necessarily mean that the old lists won't be updated, but they're not a priority.<br/><br/>Select Minecraft version to display mods for below.<br/></br>The only real criteria needed to have a mod added to the list is that I am provided with a link to said mod and that the mod isn't one generated by any sort of "Mod Maker" program/mod.</p>


<p class="select">
	<span class="section">Current:</span><br/>
	<span style="text-size:30px; font-style:italic">Last Updated: <?php $content = file('versions/changelog.txt'); echo $content[0]; ?></span><br/>
		<span class="selection"><a href="versions/1.4.6_1.4.7.php">1.4.6/1.4.7 List</a></span><br/>
		<span class="selection"><a href="versions/changelog.txt">Changelog</a></span><br/><br/>
		
	<span class="section">Older:</span><br>
		<span class="selection">1.4.4/1.4.5 List</span><br>
		<span class="selection">1.4.2 List</span><br>
		<span class="selection">1.3.2 List</span>
</p></center>


</body>