<!doctype html><html><head><meta charset="utf-8">	<title>MCF Mod List - 1.4.4/1.4.5</title>		<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>		<script type="text/javascript" src="../resources/js/tableSearch.js">/*Search script courtesy of Vattic*/</script>	<link rel="stylesheet" type="text/css" href="../resources/stylesheets/modlist.css" media="screen" />		<link rel="stylesheet" type="text/css" href="../resources/stylesheets/nav.css" media="screen" /></head>  <body>	<center>		<p>			<img src="../resources/images/1.4.4_1.4.5.png" width="239" height="47"/><br/>			<span style="font-size:200%">Last Updated: <?php $content = file('changelog_1.4.4_1.4.5.txt'); echo $content[0]; ?></span><br/><a href="changelog_1.4.4_1.4.5.txt" class="ns">Click here</a> to view the changelog.		</p>			<ul id="list-nav">		<li><a href="../">Home</a></li>		<li><a href="../credits/">Credits</a></li>		<li><a href="../latest/">Current List</a></li>		<li><a href="../banners/">Banners</a></li>	</ul>					<br/><hr width="99%" size="6" noshade>			<p style="font-size:2em">These older lists will no longer be updated. More recent lists are the priority. <a href="../latest/" class="ns">Click here</a> to the see the latest list.</p>		<table class="listnav nav">		<thead>			<th colspan="2" style="color: black">List Version Navigation</th>		</thead>				<tbody>			<tr>				<td class="h">1.4.4/1.4.5</td>				<td class="nh"><a href="../latest/">Newer Lists</a></td>			</tr>		</tbody>	</table>		<table cellspacing="0" class="modlist" id="example">		<thead>			<th style="min-width:262px">Mod Name<br/><input style="display:none" class="searchEmpty" /></th>			<th style="min-width: 50px; max-width:51px">Info</th>			<th>Author</th>			<th>Mode Availability</th>			<th>Compatibility with Forge</th>		</thead>		<tbody><!----------------------------------------------------------#-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1252066-">3D Items</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Quintinity</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr><!----------------------------------------------------------A-------------------------------------------------------->
<tr><td><a href="http://www.siedler25.org/uploads/minecraft/AdditionalBuildcraftObjects/3.2.0/">Additional Buildcraft Objects</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Flow86</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="https://github.com/tcooc/AdditionalPipesBC/downloads">Additional Pipes</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>DaStormBringer</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/690142-">Advanced HUD</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>TurboSlow</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://forum.industrial-craft.net/index.php?page=Thread&amp;threadID=4907">Advanced Machines</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>AtomicStryker</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/762794-">Animal Bikes</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Noppes</td> <td>SSP SMP LAN</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1560133-">Animal Packer</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Leondrel</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1599479-">Arcane Ascension</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>calebmanley</td> <td>SSP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1362011-">Armor Movement Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>JSut210</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1486184-">Ars Magica</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Mithion</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1462504-">AssassinCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>castielq</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1576406-">Assassin's Creed Gun/Weapon Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>senpaisubaraki</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://calclavia.com/universalelectricity/?m=18&amp;p=downloads">Assembly Line</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Calclavia</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1458795-">Atomic Science</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Calclavia</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.atomicstryker.net/">AtomicStryker's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td><td>AtomicStryker</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1126195-">AtmosMobs</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Daveyx0</td> <td>SSP</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------C-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1492661-">Backpacks</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Eydamos</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://ichun.us/mods/back-tools/">Back Tools</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>iChun</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1499035-">Bacon Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>MinecraftWero</td> <td>SSP SMP LAN</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/211517-">Balkon's WeaponMod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>BalkondeurAlpha</td> <td>Universal</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1510109-">Better Breeding Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>senpaisubaraki</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1142084-">BetterFonts</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>thvortex</td> <td>Clientside Mod</td> <td class="na">N/A</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/869534-">Better Furnaces</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>TheFrogMC</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1451360-">Better Sprinting</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>chylex</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/253365-">Better Than Wolves Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>FlowerChild</td> <td>SSP SMP</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1070207-">Better World Generation 3</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>ted80</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1495041-">Biomes O' Plenty</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>TDWP_FTW</td> <td>SSP</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1567329-">Bladecraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>DarkHax</td> <td>SSP SMP LAN</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1213268-">BlockPhysics Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>id_miner</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1161861-">Blubbeltasche's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Blubbeltasche</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1126542-">BuddyCam</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>romibi</td> <td>SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.mod-buildcraft.com/2012/11/20/buildcraft-3-2-0-for-minecraft-1-4-5/">Buildcraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>SirSengir</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1514724-">BuildRegion</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>bencvt</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr><!----------------------------------------------------------C-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/938825-">Camera Studio</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Sushen</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1348036-">Camo Lights Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phobophobe</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1548102-">CapeCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>djmati11</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1570511-">Cave-Gen Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>-Reaper-</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/909223-">Chickenbones Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>chicken_bones</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/842878-">ChristmasCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Newt_Head</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1579642-">Christmas Festivities Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>eekysam</td> <td>SSP LAN</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/964897-">Clay Soldiers Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>SanAndreasP</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.planetminecraft.com/mod/clay-tools-/">Clay Tools</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>condo97</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1568105-">Clean UI</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>sprolsly</td> <td>Clientside Mod</td> <td class="na">N/A</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1082754-">CocoaCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>-Reaper-</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1517048-">Coloured Beds Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Gorion91</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1579721-">Commander Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Visudex</td> <td>SSP</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/892282-">ComputerCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>dan200</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1487828-">Condensed Blocks Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Fenrir00</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/355537-">ControlPack</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>infinitiesloop</td> <td>Clientside Mod</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/731133-">CraftGuide</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Uristqwerty</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1483273-">CreepyPastaCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phuck_Yu_Too</td> <td>N/A</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.micdoodle8.com/crossbow.html">Crossbow Mod 2</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>micdoodle8</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1468127-">Crudedragos's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Crudedragos</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1080677-">Custom Mob Spawner</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>DrZhark</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/833003-">Custom NPCs</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Noppes</td> <td>SSP SMP LAN</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------D-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1009577-">DaftPVF's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>bspkrs <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1536685-">Damage Indicators</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>rich1051414</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1398968-">Davidee's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Davidee <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1304383-">DayZ Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>creator_admin</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1340251-">Desired Blocks</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phobophobe</td> <td>SSP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1268800-">Desperation Food</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phobophobe</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1518578-142forgedivinerpg-5-new-dimensions-50-new-mobsbosses-hundreds-of-itemsblocks-regular-updates-an-even-spookier-update/page__hl__%20divinerpg">DivineRPG</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Xolova</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/395829-">Double Door Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>kirsybuu</td> <td>SSP SMP LAN</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/827863-">Dragon Mounts</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>BarracudaATA</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1598971-">DupleCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Cannash54</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1437312-">Durability101</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>RedBanHammer</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1032511-">Dynamic Mazes</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>-Reaper-</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1543523-">Dynmap</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>mikeprimm</td> <td>SMP</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------E-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/632878-">Eastonium147's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Eastonium147</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1558714-">Easy Crafting</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Lepko</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1589367-">EasyDiamond</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>icynewyear</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1290438-">Easy Dyes Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phobophobe</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://calclavia.com/universalelectricity/?m=4">Electric Expansion</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Mattredsox and Alex_Hawks</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/498342-">Elemental Creepers</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>xSmallDeadGuyx</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/193443-">Ellian's MaterialDetector</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Ellian</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1568267-">Emasher's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Emasher</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1528282-">Enchanting Plus</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>mssodin28</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1565833-">Enhanced Books</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>sn0re</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1301217-">Enhanced Portals</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Alz454</td> <td>SSP SMP LAN</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1563097-">Epicarno Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>01110111010</td> <td>SSP LAN</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1540010-">Equivalent Exchange 3</a> (Prerelease)</td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Pahimer</td> <td>Universal</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1508146-">EssentialCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Modbder</td> <td>SSP SMP LAN</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1580364-">Exter's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>EXTER6</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/830138-">Explosives+</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Pheenixm</td> <td>SSP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1324321-">Extra Bees</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Binnie</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1090288-">ExtraBiomesXL</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>MisterFiber</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------F-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1351802-">Factorization</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>neptunepink</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1490745-">FactoryCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>TheMajorStudios</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/989113-">Falling Meteors Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>AlexDGr8r</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/931546-132sspsmplan-familiars-new-navi-rana-companioncube/">Familiars</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>pitman-87</td> <td>SSP SMP LAN</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1153874-">Father Toast's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>FatherToast</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/586218-">Fearitude's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Fearitude</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/392218-">FlintCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>666mayhem666</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://forestry.sengir.net/wiki/index.php?action=home">Forestry</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>SirSengir</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://files.minecraftforge.net/">Forge</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>LexManos</td> <td>Universal</td> <td class="fr">Forge Itself</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1519278-">Forgotten Nature</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Nightshade_Proleath</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------G-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1570071-">Glass Tools Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>bigDon_001</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/944547-">Glowstone Wire</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>GrygrFlzr</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/747246-">Goblins</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Sartharis</td> <td>SSP LAN</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://ichun.us/mods/gravity-gun/">Gravity Gun</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>iChun</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/GregsBlocks/">Greg's Blocks</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>gcewing</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/GregsLighting/">Greg's Lighting</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>gcewing</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/GregsProspecting/">Greg's Prospecting</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>gcewing</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/971353-">Grey Goo Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>stevenrs11</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/612536-">GuiAPI</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>ShaRose</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1112856-">Gulliver the Resizing Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>UncleMion</td> <td>SSP SMP</td> <td class="nfc">Not Forge Compatible</td></tr><!----------------------------------------------------------H-------------------------------------------------------->
<tr><td><a href="http://calclavia.com/universalelectricity/?m=34">Hawk's Machinery</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Elusivehawk</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1559273-">HD Skins and Cloaks</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>denoflions</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1050087-">Herblore Mod</a> (ages 18+ only)</td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>calebmanley</td> <td>SSP</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/511421-">Herobrine Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>burnner_</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/716219-">Heuristix's TheGunMod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Heuristix</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/96903-">Humans+</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Mr. okushama</td> <td>N/A</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------I-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1206144-">ICBM - Missiles and Military Tech</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Calclavia</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1545610-">Ice Cream Sandwich Creeper Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>IrunoHatake</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/366377-">ID Resolver</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>ShaRose</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1001131-">Immibis's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>immibis</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/521617-">InfiCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>mDiyo</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1558668-">In-game NBTEdit</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Davidee</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1391275-">Insta House Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phobophobe</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://forum.industrial-craft.net/index.php?page=Thread&amp;threadID=8375">IndustrialCraft 2</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Alblaka</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1608832-">Ingame Mod List</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Vazkii</td> <td>Clientside Mod</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/323444-">Inventory Tweaks</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>jimeowan</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/981855-">IronChests</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>cpw</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/563257-">Ivorius' Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Ivorius</td> <td>N/A</td> <td class="na">N/A</td></tr><!----------------------------------------------------------J-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1503486-">Jaffas and More</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>monnef</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1098808-">Jammy Furniture Mod</a> (Beta)</td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Jammy780</td> <td>Universal</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1017719-">JSOne Studios' Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>JSOne_Studios</td> <td>N/A</td> <td class="na">N/A</td></tr><!----------------------------------------------------------K-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforge.net/forum/index.php/topic,3254.0.html">Keepcalm's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>KeepCalm</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1513029-">Kirwi's Clay Golem Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Kirwii</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr><!----------------------------------------------------------L-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1477655-">Layman Mod Maker</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Vazkii</td> <td>SSP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1445361-">Legendary Beasts</a> (a)</td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Davidee</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1458931-">LibShapeDraw</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>bencvt</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1547522-">Lighting Fix</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>silverwind213</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/954187-125-132-pre-release-the-lion-king-mod-v151/">Lion King Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Mevans</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://slimevoid.net/littleblocks/">LittleBlocks</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>VengeurK</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1588265-">litteMaidMod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>eromanrocks</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1575883-">Lockit</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>hypercross</td> <td>SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://ci.thezorro266.com/job/LogisticsPipes/">Logistics Pipes</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>thezorro266</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1554802-">LOLCaatz's Clientside Tweaks</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>LOLCaatz</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr><!----------------------------------------------------------M-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/467504-">Macro/Keybind Mod and LiteLoader</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Mumfrey</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1570989-">MapWriter Mini Map Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>mapwriter</td> <td>Clientside Mod</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/330485-">Marcopolo's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>marcopolo1613</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/379925-">MAtmos</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Hurricaaane</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1146661-">MCDitty</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>fenceFoil</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1565667-">Meat+</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Inofficially</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1604705-">MegaCraft Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>NielsSrychi</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://calclavia.com/universalelectricity/?m=17">Mekanism</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Aidancbrady</td> <td>Universal</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/744918-">Metallurgy 2</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Shadowclaimer</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://millenaire.org/">Millénaire</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Kinniken</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1542377-">Mine &amp; Blade: Commander</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>nerd-boy</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/758734-">Minecraft Capes</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>cjz__</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1139619-">Minecraft My Way mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>WyrdOne</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1238049-">MineFantasy</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>AnonymousProductions</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/748553-">MineLittlePony</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Verdana</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1270694-">Mining Enhancemants</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phobophobe</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1609218-">M-Food</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Kuuu</td> <td>SSP</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1573550-">M-Ore Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Kuuu</td> <td>SSP</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/81771-">Mo' Creatures</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>DrZhark</td> <td>Universal</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1271059-">Mo' Minecraft Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>VorlockMAN</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://ichun.us/mods/mob-amputation/">Mob Amputation</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>iChun</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://ichun.us/mods/mob-dismemberment/">Mob Dismemberment</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>iChun</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1553186-">Mob Spawn Controls</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Davidee</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1163014-">ModOptionsAPI</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>WyrdOne</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1458328-">Mods by Kinyoshi</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Kinyoshi</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1559970-">More Bows Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>iDiamondhunter</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1357421-">More Enchantments Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>glider521al</td> <td>SSP LAN</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/877105-">More Explosives</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>NikolaiTheEpicGenius</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1483310-">More Fences Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>bobbyjoe2</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1122495-">More Player Models</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Noppes</td> <td>SSP SMP LAN</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1543706-">More Pressure Plates Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>bobbyjoe2</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1430150-">More Village Biomes + Village Logic Addon</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>shortwind</td> <td>SSP SMP</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1138477-">More Swords Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>DarkHax</td> <td>SSP SMP LAN</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1170158-">MorpheusZero's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>MorpheusZero</td> <td>Universal</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1518185-">Mouse Tweaks</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>YaLTeR97</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1528715-">Moustaches and More</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phobophobe</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1565670-">Multi Crafting Table</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>dmillerw</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1243270-">MusicCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phuck_Yu_Too</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1336132-">Mutant Creatures</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>thehippomaster21</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://binarymage.com/">Mystcraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>XCompWiz</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1580603-">MysticRPG</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>oitsjustjose</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------N-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1577895-">Not in Minecraft Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>01110111010</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr><!----------------------------------------------------------O-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1453823-">Obsidia: The power of Obsidian</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>senpaisubaraki</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/249637-">Optifine</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>sp614x</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr><!----------------------------------------------------------P-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1383295-">Pacman Arcade</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Formulayeti</td> <td>Universal</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/309199-">Paintball</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>lkinx</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1534970-">PaintGun Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>rich1051414</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/402069-">Pam's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>MatrexsVigil</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://ichun.us/mods/pig-grinder/">Pig Grinder</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>iChun</td> <td>SSP LAN</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1276311-">Pixelmon</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>epicSplashBattle</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1567105-">PizzaCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Callumz07</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/738498-142api-player-api/">Player API</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Divisor</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1253666-">Plugins for Forestry</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>denoflions</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/400275-">Poop Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Tominator1</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/199391-">Portal Gun - Reconstructed</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>iChun</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://calclavia.com/universalelectricity/?m=16">PowerTools</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Eearslya</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1589790-">Power Swords Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>chri60a1</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1319748-">Precious Gems Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phobophobe</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr><!----------------------------------------------------------Q--------------------------------------------------------><!----------------------------------------------------------R-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/701990-">Railcraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>CovertJaguar</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1581930-">rbdyck's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>rbdyck</td> <td>SSP</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1535339-">Reactioncraft Better Bookcases</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>eragonn1490</td> <td>SSP SMP LAN</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1607782-">Reactioncraft Better Glass</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>eragonn1490</td> <td>SSP SMP LAN</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1581608-">Reactioncraft Mobs Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>eragonn1490</td> <td>SSP SMP LAN</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1538598-">RealLan</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>RealLan</td> <td>Clientside Mod</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/482147-">Rei's Minimap</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>ReiFNSK</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/75440-">Risugami's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Risugami</td> <td>N/A</td> <td class="na">N/A</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1487712-">Rotten Flesh to Leather</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>EpicBlargh</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr><!----------------------------------------------------------S-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/546192-">Secret Rooms Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>AbrarSyed</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1544812-">ShowMonsters</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>KaboPC</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/902350-minecraft-142-simpleores-mod-ssp-smp/">SimpleOres</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>AleXndrTheGr8st</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/94310-">Single Player Commands</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>simo_415</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://ichun.us/mods/slender-reimagined/">Slender - Reimagined</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>iChun</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1342652-">Slender Man</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>colossali</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/361430-142smp-smart-moving/">Smart Moving</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Divisor</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1515587-">Soda Craft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phobophobe</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/579177-">Sophisticated Wolves</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>metroidfood</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1543706-">Spawn Eggs Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>bobbyjoe2</td> <td>SSP</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/702878-">Sports Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>nico910</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1575294-">StrongerPistons Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>MinecraftShamrock</td> <td>SSP SMP</td> <td class="na">N/A</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1460246-">Subarakis Secondary Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>senpaisubaraki</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1489459-">Super Heroes in Minecraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>colossali</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/680276-">Steve's Carts 2</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Vswe</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1430913-">S.T.F.U.</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>RedBanHammer</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/545791-">Super Mario Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Jimboom7</td> <td>SSP SMP LAN</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------T-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1540451-">TabbyChat</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>RocketMan10404</td> <td>SMP</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1468927-">Tale of Kingdoms</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>aginsun</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/334760-">Team Fortress 2 Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>pitman-87</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1500487-">Teleportation Stones</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>dmillerw</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://terrafirmacraft.com/">TerraFirmaCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>bioxx</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1585216-">Thaumcraft 3</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Azanor</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/753030-">TheBombzen's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>thebombzen</td> <td>N/A</td> <td class="na">N/A</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/508821-">The Car Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>mermz</td> <td>N/A</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1485997-">The Death Scythe Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Kirwii</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1558952-">The Elder Scrolls: Skyrim Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>sheenrox82</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1513613-">The Infection</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Tynarus</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1546552-">The Mineya Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>senpaisubaraki</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1571429-">The Necromancy Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>sirolf2009</td> <td>N/A</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/851939-">The RC Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Skerp</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/950541-">The Runic Dust Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>billythegoat101</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1420958-">The Wars Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>resinresin</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1297506-">Thermal Expansion</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>KingLemmingCoFH</td> <td>Universal</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/119361-">Timber!</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>TehKrush</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/140684-">TooManyItems</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Marglyph</td> <td>Clientside Mod</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1477908-">TooManyPlants</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>benzrf</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1119809-">Torojima's Chococraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Torojima</td> <td>Universal</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1587267-">Traincraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Traincraft</td> <td>SSP SMP LAN</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/533512-">Tropicraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Cojomax99</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1574092-">TukMC</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Vazkii</td> <td>Clientside Mod</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/561673-">Twilight Forest</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Benimatic</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------U-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1104963-">Ultimate Tools</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Umbrosus</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1276496-">Universal Electricity</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Calclavia</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1584001-">Urban Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Westfaliaforever</td> <td>N/A</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1355433-">UseCount 2</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>TheWhiteWolves</td> <td>Clientside Mod</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1378111-">Usefulfood</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Silentspy</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------V-------------------------------------------------------->
<tr><td><a href="https://github.com/denoflionsx/DenPipes/wiki">Valve Pipes</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>denoflionsx</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1298016-">Vanilla with Sprinkles</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Koopinator</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/528166-">Vazkii's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Vazkii</td> <td>N/A</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------W-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1417685-">Wasteland mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>thegamingwolfs</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1486452-">WiNeTel's BetterWorld Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>WiNeTel</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/328725-">Wireless Redstone</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>ali4z</td> <td>SSP SMP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1366410-">Witches and More</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Chancebozey</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1574999-">Wolves+ Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Willsr71</td> <td>N/A</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1444862-">World Downloader</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>cubic72</td> <td>SMP</td> <td class="nfc">Not Forge Compatible</td></tr><!----------------------------------------------------------X-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/867079-">X-Ray Mod</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>craftminer502</td> <td>N/A</td> <td class="nfc">Not Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1596973-">Xeno's Reliquary</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>x3n0ph0b3</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/477267-">Xie's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Xie</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>
<tr><td><a href="http://xycraft.wikispaces.com/Home">XyCraft</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Soaryn</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr><!----------------------------------------------------------Y-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1550986-">You are the Wither</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>albert721</td> <td>SSP</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1519073-">Your Ore</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Phobophobe</td> <td>N/A</td> <td class="fc">Forge Compatible</td></tr>
<tr><td><a href="http://www.minecraftforum.net/topic/1543355-">Yourock129's Mods</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>yourock129</td> <td>N/A</td> <td class="na">N/A</td><!----------------------------------------------------------Z-------------------------------------------------------->
<tr><td><a href="http://www.minecraftforum.net/topic/1451798-">Zaedes' Steamworks</a></td> <td class="desctd"><span class=""><!--INFO--></span></td> <td>Zaedes</td> <td>SSP SMP</td> <td class="fr">Forge Required</td></tr>

</tbody></table></center><br/><div class="footer">	Mod count: <b>270</b></div><!--Google Analytics--><script type="text/javascript">  var _gaq = _gaq || [];  _gaq.push(['_setAccount', 'UA-39433845-1']);  _gaq.push(['_trackPageview']);  (function() {    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);  })();</script></body></html>