<div class="page-header">
    <h1>Submission Form</h1>
</div>
<!-- 
TODO: alerts
<div class="alert alert-dismissable alert-warning">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Warning:</strong> This version is no longer supported and will no longer receive updates.
</div>
-->
<?php if('success' === $this->state) { ?>
<div class="alert alert-dismissable alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Well done!</strong> You successfully submitted the mod.
</div>
<?php } elseif('failed' === $this->state) { ?>
<div class="alert alert-dismissable alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Uh oh!</strong> Something went wrong on our side. Please notify us about this problem.
</div>
<?php } elseif('incomplete' === $this->state) { ?>
<div class="alert alert-dismissable alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Uh oh!</strong> You haven't filled out all the required fields!
</div>
<?php } ?>
<form role="form" method="POST" action="complete">
    <div class="form-group">
        <div class="btn-group" id="request-type-group">
            <label class="active">
                <input type="radio" name="request-type" id="new" value="new" checked> New Mod
            </label>
            <label>
                <input type="radio" name="request-type" id="old" value="old"> Update Request
            </label>
        </div>
    </div>
    <div class="form-group">
        <label for="name">Mod Name</label>
        <input type="text" class="form-control typeahead" name="name" id="name" placeholder="Name of the mod" required autofocus>
    </div>
    <div class="form-group">
        <label for="link">Link</label>
        <input type="url" class="form-control" name="link" id="link" placeholder="Link to the site, page or thread of the mod if available">
    </div>
    <div class="form-group">
        <label for="desc">Description</label>
        <textarea class="form-control" rows="3" name="desc" id="desc" placeholder="What does the mod do? Be as clear and concise as possible."></textarea>
    </div>
    <div class="form-group">
        <label for="authors">Mod Authors</label>
        <input type="text" class="form-control" name="authors" id="authors" placeholder="Enter the author(s) of the mod, comma separated">
    </div>
    <div class="form-group">
        <label for="source">Source</label>
        <input type="url" class="form-control" name="source" id="source" placeholder="Link to site or page of the mod source code">
    </div>
    <div class="form-group" id="forge-compatibility">
        <label for="forge-compatibility">Forge Compatibility</label>
        <div class="radio">
            <label>
                <input type="radio" name="forge" id="required" value="required" checked>
                Forge Required - This mod needs Forge to run.
            </label>
        </div>
        <div class="radio">
            <label>
                <input type="radio" name="forge" id="compatible" value="compatible">
                Forge Compatible - This mod can run alongside Forge, but doesn't require it. Most Modloader mods can be loaded by Forge.
            </label>
        </div>
        <div class="radio">
            <label>
                <input type="radio" name="forge" id="notcompatible" value="notcompatible">
                Not Forge Compatible - This mod cannot run alongside Forge.
            </label>
        </div>
    </div>
    <div class="form-group" id="availability">
        <label for="availability">Availability</label>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="Universal" name="availability[]">
                Universal - The mod has the same file that can run on both Singleplayer and Multiplayer, and is not Client-only or Server-only.
            </label>
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="Client" name="availability[]">
                Clientside - The mod only needs to run on the client. Example: Minimaps
            </label>
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="Server" name="availability[]">
                Serverside - The mod only needs to run on the server. Example: Extra Commands
            </label>
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="SSP" name="availability[]">
                SSP - The mod works in Singleplayer, and does not have a universal mod file.
            </label>
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="SMP" name="availability[]">
                SMP - The mod works in Multiplayer, and does not have a universal mod file.
            </label>
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="LAN" name="availability[]">
                LAN - The mod works in LAN, and does not have a universal mod file.
            </label>
        </div>
    </div>
    <div class="form-group" id="versions">
        <label for="versions">Versions</label>
        <?php foreach($this->versions as $version) { ?>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="<?php echo $version; ?>" name="versions[]">
                <?php echo $version; ?>
            </label>
        </div>
        <?php } ?>
    </div>
    <div class="form-group">
        <label for="other">Other</label>
        <textarea class="form-control" rows="3" name="other" id="other" placeholder="Any other information you want to tell us?"></textarea>
    </div>
    <textarea id="nothuman" name="nothuman" placeholder="Do NOT type anything in this box or you will be BLACKLISTED"></textarea>
    <button type="submit" class="btn btn-primary" data-loading-text="Submitting...">Submit</button>
    <button type="reset" class="btn btn-default">Reset</button>
</form>