<style>
h1, h2 {
	border-bottom: 1px solid black;
}
.reserved {
	font-family: monospace;
}
table, .code {
	margin-left: 32px;
	margin-right: 32px;
	background-color: white;
}
table {
	border: 1px solid black;
}
.code {
	border: 1px dashed black;
	max-height: 300px;
	overflow: auto;
}
table tr th, table tr td {
	max-width: 450px;
	text-align: center;
	border: 1px solid black;
}
table tr th {
	font-weight: bold;
}
#bottomspacer {
	padding: 16px;
	font-style: italic;
}
</style>
<h1>Modlist APIv2</h1>
<h2>APIv2 Requests</h2>
<p>
	APIv2 Requests use apiv2.php on the root of the site (<a href="http://modlist.mcf.li/apiv2.php">http://modlist.mcf.li/apiv2.php</a>).<br/>
	You can register for an account and API key <a href="http://modlist.mcf.li/panel/register.php">here</a>.<br/>
	Requests are executed by attaching a GET request in the following form:
</p>
<table>
	<tr>
		<th>Key</th>
		<th>Value Type</th>
		<th>Accepted Values</th>
	</tr>
	<tr>
		<td>key</td>
		<td>string</td>
		<td>alphanumeric md5 generated in panel</td>
	</tr>
	<tr>
		<td>request</td>
		<td>string</td>
		<td><span class="reserved">hash</span>, <span class="reserved">json</span></td>
	</tr>
	<tr>
		<td>version</td>
		<td>string</td>
		<td><span class="reserved">all</span>, <span class="reserved">1.6.1</span>, <span class="reserved">1.5.2</span>, <span class="reserved">1.5.1</span>, <span class="reserved">1.5.0</span>, <span class="reserved">1.5</span>, <span class="reserved">1.4.7</span>, <span class="reserved">1.4.6</span>, <span class="reserved">1.4.5</span>, <span class="reserved">1.4.4</span>, <span class="reserved">1.4.2</span>, <span class="reserved">1.3.2</span></br>or a combined request separated by an underscore</td>
	</tr>
</table>
<h3>Example Usage</h3>
<pre class="code">http://modlist.mcf.li/api.php?key=<strong>API_KEY</strong>&version=1.5.0_1.5.1_1.5.2&request=hash</pre>
<p>Will return the md5 hash for the combined request of 1.5, 1.5.1 and 1.5.2.</p>
<pre class="code">http://modlist.mcf.li/api.php?key=<strong>API_KEY</strong>&version=all&request=hash</pre>
<p>Will return the md5 hash for the combined request of all versions.</p>
<h2>Hash Request</h2>
<p>Returns an md5 check of the requested JSON file.</p>
<h3>Example</h3>
<pre class="code">http://modlist.mcf.li/api.php?key=<strong>API_KEY</strong>&version=1.5.2&request=hash</pre>
<pre class="code">fbf9cc4a8704a28045037a69908b2b97</pre>
<h2>JSON Request</h2>
<h3>Format</h3>
<pre class="code">
[
  {
    "name":"",
    "other":"",
    "link":"",
    "desc":"",
    "author":[],
	"source":"",
    "type":[""],
    "dependencies":[""],
    "versions":[""]
  }
]
</pre>
<table>
	<tr>
		<th>Key</th>
		<th>Type</th>
		<th>Notes</th>
	</tr>
	<tr>
		<td>name</td>
		<td>string</td>
		<td>Name of the mod</td>
	</tr>
	<tr>
		<td>other</td>
		<td>string</td>
		<td>Extra name in brackets - <strong>does not exist when field is empty</strong>; make sure to check for existence; previously always existed in APIv1</td>
	</tr>
	<tr>
		<td>link</td>
		<td>string</td>
		<td>Link to the mod page</td>
	</tr>
	<tr>
		<td>desc</td>
		<td>string</td>
		<td>A description of the mod</td>
	</tr>
	<tr>
		<td>author</td>
		<td>array of strings</td>
		<td>List of author(s); previously a string in APIv1</td>
	</tr>
	<tr>
		<td>source</td>
		<td>string</td>
		<td>Link to mod source code - <strong>does not exist when mod is not open source</strong>; make sure to check for existence; if empty, requires personal request to author; unused in APIv1</td>
	</tr>
	<tr>
		<td>type</td>
		<td>array of strings</td>
		<td>The type of the mod</td>
	</tr>
	<tr>
		<td>dependencies</td>
		<td>array of strings</td>
		<td>List of mod dependencies</td>
	</tr>
	<tr>
		<td>versions</td>
		<td>array of strings</td>
		<td>List of supported versions</td>
	</tr>
</table>
<p>
	The <span class="reserved">type</span> array can hold one or more of the following values:</br>
	<ul class="reserved">
		<li>Universal</li>
		<li>SSP</li>
		<li>SMP</li>
		<li>LAN</li>
		<li>Client</li>
		<li>Server</li>
	</ul></br>
	The <span class="reserved">dependencies</span> array can either be empty (treated as No Dependency) or hold one or more of the following values:
	<ul class="reserved">
		<li>Modloader</li>
		<li>Modloader Compatible</li>
		<li>Not Forge Compatible</li>
		<li>Forge Compatible</li>
		<li>Forge Required</li>
	</ul></br>
	It may also contain other dependencies such as <span class="reserved">iChun Utils</span>.
</p>
<h3>Example</h3>
<pre class="code">http://modlist.mcf.li/api.php?key=<strong>API_KEY</strong>&version=1.5.1&request=json</pre>
<pre class="code">
[
  {
    "name":"AudioMod",
    "other":"(API)",
    "link":"http://bit.ly/WnSwBj",
    "desc":"AudioMod is an upgrade of sorts, and a modder's utility. Included in this mod is CodecIBXM, created by Paul at www.paulscode.com, who is the creator of the sound system used in Minecraft. It allows Minecraft to play (in addition to ogg, wav, and mus files), xm, s3m, and mod files. The only readily available feature of this mod is the ability to add new music, however, it adds support for modders to add new records and sound effects.NOTE: Do not install this with Forge. Forge has its own version that's backwards compatible with Risugami's.",
    "author":["Risugami"],
    "type":["SSP"],
    "dependencies":["Not Forge Compatible"],
    "versions":["1.4.6","1.4.7","1.5.0","1.5.1","1.5.2","1.6.1"]
  },
  {
    "name":"Glowstone Wire",
    "link":"http://bit.ly/13BkZcS",
    "desc":"Allows you to place glowstone dust! Not only they're great for trails, they actually give out light!",
    "author":["GrygrFlzr"],
    "type":["Universal"],
    "dependencies":["Forge Compatible"],
    "versions":["1.4.2","1.4.4","1.4.5","1.4.6","1.4.7","1.5.0","1.5.1","1.5.2","1.6.1"]
  },
  {
    "name":"IronChests 2",
    "link":"http://bit.ly/ironchests2",
    "desc":"Adds chests made from different types of metal to the game. Each tier of metal chest can contain more items.",
    "author":["cpw"],
	"source":"https://github.com/cpw/ironchest/tree/master/IronChests2",
    "type":["Universal"],
    "dependencies":["Forge Required"],
    "versions":["1.4.2","1.4.4","1.4.5","1.4.6","1.4.7","1.5.0","1.5.1","1.5.2","1.6.1"]
  },
  {
    "name":"Monster Spawn Highlighter",
    "link":"http://bit.ly/Sw1AcJ",
    "desc":"This mod has separate ModLoader and Forge versions.See bit.ly/modloaderHighlights any blocks where monsters can spawn.",
    "author":["Lunatrius"],
    "type":["Client"],
    "dependencies":["Forge Compatible","Modloader Compatible"],
    "versions":["1.4.2","1.4.4","1.4.5","1.4.6","1.4.7","1.5.0","1.5.1","1.5.2"]
  }
]
</pre>
<b>Notice: Result for <span class="reserved">json</span> will be compressed for bandwidth efficiency.</b></br>
<h2>Invalid Requests</h2>
<p>An invalid request will return a json object similar to the result of a <span class="reserved">json</span> request.</p>
<table>
	<tr>
		<th>Error Code</th>
		<th>Meaning</th>
	</tr>
	<tr>
		<td>404</td>
		<td>An API Key is required to access the database</td>
	</tr>
	<tr>
		<td>403</td>
		<td>Your API Key is invalid or has been removed</td>
	</tr>
	<tr>
		<td>402</td>
		<td>A request is needed</td>
	</tr>
	<tr>
		<td>401</td>
		<td>The request does not exist</td>
	</tr>
	<tr>
		<td>400</td>
		<td>No version has been requested</td>
	</tr>
</table>
<h3>Example</h3>
<pre class="code">http://modlist.mcf.li/api.php?key=<strong>WRONG_API_KEY</strong>&version=1.5.1&request=json</pre>
<pre class="code">
[
  {
    "name":"404",
    "link":"",
    "desc":"An API Key is required to access the database",
    "author":["GrygrFlzr"],
    "type":[],
    "dependencies":["API Key"],
    "versions":[]
  }
]
</pre>
<div id="bottomspacer">Last modified by GrygrFlzr on 26 July 2013, 07:15 AM UTC Time.</div>