<div class="jumbotron">
    <h1>Banners</h1>
    <p>There should be a page here but GrygrFlzr hasn't made it yet. :P</p>
    <p>
        <a href="/version/latest" class="btn btn-primary btn-lg">Check out the latest mod list!</a>
        <a href="/history" class="btn btn-default btn-lg">What happened to the site?</a>
    </p>
</div>
<p>BBCode (For Use in Minecraft Forums!):</p>
<pre>[center]Looking for mods? Check out the [url="http://modlist.mcf.li/latest"][img]http://modlist.mcf.li/resources/images/bannerSmall.png[/img][/url][/center]</pre>