<div class="jumbotron">
    <h1>MCF Modlist</h1>
    <p>A list of Minecraft mods compiled by the community</p>
    <p>
        <a href="/version/latest" class="btn btn-primary btn-lg">Check out the latest mod list!</a>
        <a href="/history" class="btn btn-default btn-lg">What happened to the site?</a>
    </p>
</div>
<div class="row home-changelog">
    <?php $latest_versions = array_slice($this->versions, 0, 4); ?>
    <?php foreach($latest_versions as $latest) { ?>
    <div class="col-sm-6 col-lg-3">
        <h2><?php echo $latest; ?></h2>
        <p><i>Last Updated <?php echo changelogDate($latest) ?></i></p>
        <p><?php echo changelogParse($latest) ?></p>
        <p><a class="btn btn-primary" href="/version/<?php echo $latest; ?>">View list &raquo;</a> <a class="btn btn-default" href="/changelog/<?php echo $latest; ?>">View all changes &raquo;</a></p>
    </div>
    <?php } ?>
</div>