<div class="jumbotron">
    <h1>MCF Modlist</h1>
    <p>A list of Minecraft mods compiled by the community</p>
    <p>
        <a href="/version/latest" class="btn btn-primary btn-lg">Latest Mod List &raquo;</a>
        <a href="/random" class="btn btn-default btn-lg">View Random Mod &raquo;</a>
    </p>
</div>
<div class="row home-changelog">
    <?php $latest_versions = array_slice($this->versions_grouped, 0, 3); ?>
    <?php foreach($latest_versions as $group) {
        $display_versions[] = array_keys($group)[0];
    } ?>
    <?php foreach($display_versions as $latest) { ?>
    <div class="col-sm-6 col-lg-4">
        <h2><?php echo $latest; ?></h2>
        <p><i>Last Updated <?php echo changelogDate($latest) ?></i></p>
        <p><?php echo changelogParse($latest) ?></p>
        <p><a class="btn btn-primary" href="/version/<?php echo $latest; ?>">View list &raquo;</a> <a class="btn btn-default" href="/changelog/<?php echo $latest; ?>">View all changes &raquo;</a></p>
    </div>
    <?php } ?>
</div>