<table class="table table-hover">
    <thead>
        <tr>
            <th>Version List</th>
            <th>Mods listed</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->versions as $version) { ?>
        <tr>
            <td><a href="/version/<?php echo $version; ?>"><?php echo $version; ?></a></td>
            <td><?php echo $this->versions_count[$version] ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>