<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#" lang="en">
<head>
    <meta charset="utf-8">
    <title><?php if(isset($this->title)) { echo $this->title . ' - '; } ?>MCF Mod List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Minecraft Forum Mod List - A list of Minecraft mods compiled by the community.<?=
    isset($this->description) ? ' ' . $this->description : ''
    ?>" />
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@MCFModlist">
    <meta property="og:title" content="<?php if(isset($this->title)) { echo $this->title . ' - '; } ?>MCF Modlist">
    <meta property="og:image" content="http://modlist.mcf.li/resources/images/favicon32x32.png">
    <meta property="og:type" content="website">
    <meta name="twitter:description" property="og:description" content="Minecraft Forum Mod List - A list of Minecraft mods compiled by the community.<?=
    isset($this->description) ? ' ' . $this->description : ''
    ?>" />
    <?php if($this->uri !== '') { ?>
    <meta property="og:url" content="http://modlist.mcf.li<?=$this->uri?>">
    <?php } ?>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="/resources/stylesheets/modlist.css?v=<?=$this->cssVer?>"/>
    <script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-39433845-1', 'mcf.li');
    ga('send', 'pageview');
    </script>
    <link rel="dns-prefetch" href="//ajax.googleapis.com/"/>
    <link rel="dns-prefetch" href="//cdnjs.cloudflare.com/"/>
    <link rel="dns-prefetch" href="//bit.ly/"/>
    <link rel="dns-prefetch" href="//www.minecraftforum.net/"/>
    <link rel="shortcut icon" href="/resources/images/favicon32x32.png">
</head>
<body <?=$this->themed ? 'class="dark-body"' : ''?>>
    <nav class="navbar navbar-inverse navbar-fixed-top ml-nav <?=$this->themed ? 'ml-nav-dark' : 'ml-nav-light'?>" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">MCF Modlist</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/"><i class="fa fa-home"></i> Home</a></li>
                    <li class="dropdown">
                        <a href="/version" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-list"></i> List <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        <?php $divider = 1; ?>
                        <?php foreach ($this->versions_grouped as $group => $versions) { ?>
                            <li class="dropdown-header hidden-xs"><?php echo $group; ?></li>
                            <?php foreach ($versions as $version => $count) { ?>
                                <li class="version-link"><a href="/version/<?php echo $version; ?>"><span class="badge pull-right"><?php echo $count ?></span><span class="sr-only"> mods listed on </span><?php echo $version; ?></a></li>
                            <?php } ?>
                            <?php if($divider < count($this->versions_grouped)) { ?><li class="divider"></li><?php } ?>
                            <?php $divider++; } ?>
                        </ul>
                    </li>
                    <li><a href="/submit"><i class="fa fa-edit"></i> Submit Mods</a></li>
                    <li><a href="/faq"><i class="fa fa-question-circle"></i> FAQ</a></li>
                    <li class="dropdown">
                        <a href="/other" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-external-link"></i> More <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/random">Random Mod</a></li>
                            <li><a href="/api/v3/docs">API Docs</a></li>
                            <li><a href="/changelog">Changelog</a></li>
                            <li><a href="/banners">Banners</a></li>
                            <li><a href="/history">History</a></li>
                            <li><a href="/credits">Credits</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="https://twitter.com/MCFModlist"><i class="fa fa-tw"></i><span class="hidden-md-nav"> Twitter</span></a></li>
                    <li class="dropdown">
                        <a href="/options" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-gear"></i><span class="hidden-md-nav"> Options</span></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Theme</li>
                            <li><a href="/options/theme/light">Light</a></li>
                            <li><a href="/options/theme/dark">Dark</a></li>
                            <li class="divider"></li>
                            <li><a href="/options">Options Page</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <ul class="breadcrumb hidden-print">
            <?php echo breadcrumbs(); ?>
        </ul>
        <?php echo $this->yieldView(); ?>
    </div>
    <div class="modal fade" id="alert" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/resources/js/jquery.stickytableheaders.min.js"></script>
    <script type="text/javascript" src="/resources/js/tooltips.min.js"></script>
    <script type="text/javascript" src="/resources/js/search.min.js"></script>
    <?php if(isset($this->specialjavascripts)) {
        foreach ($this->specialjavascripts as $javascript) { ?>
    <script type="text/javascript" src="<?php echo $javascript; ?>"></script>
    <?php }} ?>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</body>
</html>
<?php
//TODO: Refactor and cleanup breadcrumbs code
function breadcrumbs($separator = "</li>\n<li>", $home = 'Home') {
    $path = array_filter(explode('/', parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)));
    $base = '/';
    $breadcrumbs = Array("<a href=\"$base\">$home</a>");
    $last = end(array_keys($path));

    foreach ($path AS $x => $crumb) {
        $title = ucwords(str_replace(Array('.php', '_'), Array('', ' '), $crumb));

        if ($title === "Faq")
            $title = "FAQ";
        if ($title === "Igml")
            $title = "IGML";

        if ($x !== $last)
            $breadcrumbs[] = "<a href=\"$base$crumb\">$title</a>";
    }

    if (isset($title))
        return '<li>' . implode($separator, $breadcrumbs) . '</li>' . "\n" . '<li class="active">' . $title . '</li>';
    else
        return '<li class="active">Home</li>';
}
?>