<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?php if(isset($this->title)) { echo $this->title . ' - '; } ?>MCF Mod List Panel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Minecraft Forum Mod List - A list of Minecraft mods compiled by the community" />
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="/resources/stylesheets/modlist.css"/>
    <link rel="stylesheet" href="/resources/stylesheets/panel.css"/>
    <link rel="dns-prefetch" href="//www.google-analytics.com"/>
    <link rel="dns-prefetch" href="//ajax.googleapis.com/"/>
    <link rel="dns-prefetch" href="//cdnjs.cloudflare.com/"/>
    <link rel="dns-prefetch" href="//bit.ly/"/>
    <link rel="dns-prefetch" href="//www.minecraftforum.net/"/>
    <link rel="shortcut icon" href="/resources/images/favicon32x32.png">
</head>
<body <?=$this->themed ? 'class="dark-body"' : ''?>>
    <nav class="navbar navbar-inverse navbar-fixed-top ml-nav <?=$this->themed ? 'ml-nav-dark' : 'ml-nav-light'?>" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/panel/home">MCF Modlist Panel</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/panel/home">Home</a></li>
                    <li><a href="/panel/submission">Submissions</a></li>
                    <li><a href="/panel/queue">Queue</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="" class="dropdown-toggle" data-toggle="dropdown"><?php echo $_SESSION['user']; ?> <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                            <li class="dropdown-header">Theme</li>
                            <li><a href="/options/theme/light">Light</a></li>
                            <li><a href="/options/theme/dark">Dark</a></li>
                            <li class="divider"></li>
                            <li><a href="/panel/logout">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <?php echo $this->yieldView(); ?>
    </div>
    <div class="modal fade" id="alert" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/resources/js/jquery.stickytableheaders.min.js"></script>
    <script type="text/javascript" src="/resources/js/tooltips.min.js"></script>
    <script type="text/javascript" src="/resources/js/panel.min.js"></script>
    <?php if(isset($this->specialjavascripts)) {
        foreach ($this->specialjavascripts as $javascript) { ?>
    <script type="text/javascript" src="<?php echo $javascript; ?>"></script>
    <?php }} ?>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</body>
</html>