<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>MCF Mod List - <?php echo $this->title; ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="Minecraft Forum Mod List - A list of Minecraft mods compiled by the community" />
        <?php
        // TODO: make this more efficient
        $stylesheets = array(
            "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.no-icons.min.css",
            "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css",
            "/resources/stylesheets/modlist-blue.css",
            "/resources/stylesheets/panel.css"
        );
        $prefetches = array(
            "//www.google-analytics.com",
            "//ajax.googleapis.com/",
            "//cdnjs.cloudflare.com/",
            "//bit.ly/",
            "//www.minecraftforum.net/",
        );
        $javascripts = array(
            "//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js",
            "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js",
            "/resources/js/jquery.stickytableheaders.min.js",
            "/resources/js/tooltips.js",
        );
        ?>
        <?php foreach ($stylesheets as $stylesheet) { ?>
        <link rel="stylesheet" href="<?php echo $stylesheet; ?>"/>
        <?php } ?>
        <?php foreach ($prefetches as $prefetch) { ?>
        <link rel="dns-prefetch" href="<?php echo $prefetch; ?>"/>
        <?php } ?>
	<link rel="shortcut icon" href="/resources/images/favicon32x32.png">
	<link rel="canonical" href="." />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top ml-nav-blue" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">MCF Modlist</a>
            </div>
        </div>
    </nav>
    <div class="container">
        <?php echo $this->yieldView(); ?>
    </div>
    <?php if(isset($this->specialjavascripts))
        $javascripts = array_merge($javascripts, $this->specialjavascripts);
    foreach ($javascripts as $javascript) { ?>
    <script type="text/javascript" src="<?php echo $javascript; ?>"></script>
    <?php } ?>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script>
    <![endif]-->
</body>
</html>