<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>MCF Mod List<?php if(isset($this->title)) { echo ' - ' . $this->title; } ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Minecraft Forum Mod List - A list of Minecraft mods compiled by the community" />
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="/resources/stylesheets/modlist-blue.css"/>
    <link rel="stylesheet" href="/resources/stylesheets/panel.css"/>
    <link rel="dns-prefetch" href="//www.google-analytics.com"/>
    <link rel="dns-prefetch" href="//ajax.googleapis.com/"/>
    <link rel="dns-prefetch" href="//cdnjs.cloudflare.com/"/>
    <link rel="dns-prefetch" href="//bit.ly/"/>
    <link rel="dns-prefetch" href="//www.minecraftforum.net/"/>
    <link rel="shortcut icon" href="/resources/images/favicon32x32.png">
</head>
<body>
    <?php echo $this->yieldView(); ?>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/resources/js/jquery.stickytableheaders.min.js"></script>
    <script type="text/javascript" src="/resources/js/tooltips.js"></script>
    <?php if(isset($this->specialjavascripts)) {
        foreach ($this->specialjavascripts as $javascript) { ?>
    <script type="text/javascript" src="<?php echo $javascript; ?>"></script>
    <?php }} ?>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</body>
</html>