<div class="media">
    <img class="media-object img-rounded pull-left avatar-home"
         alt="<?php echo $_SESSION['user']; ?>'s avatar"
         src="<?php echo $_SESSION['avatar']; ?>&s=128" />
    <div class="media-body">
        <h4 class="media-heading">
            <?php echo $_SESSION['user']; ?>
        </h4>
        <p class="text-muted">Last logged in 18th of November, 2013</p>
    </div>
</div>