<div class="page-header">
    <h1><?=$this->version ?><br/>
        <small>Tracking <?=$this->versions_count[$this->version] ?> mods for this version - <a href="/changelog/<?=$this->version ?>">View Changelog</a></small>
    </h1>
</div>
<!-- 
TODO: supported?
<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Warning:</strong> This version is no longer supported and will no longer recieve updates.
</div>
-->
<?php if($this->version === '1.7.2') { ?>
<div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    Keep in mind this is a large update - do not ask mod developers for ETAs.
</div>
<?php } elseif($this->version === '1.7.10-pre4') { ?>
<div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>This is a pre-release.</strong> Backup your worlds, bugs are likely to occur.<br>
    Some of these may be listed as 1.7.2-compatible only but have been tested to work on this version.<br>
    Keep in mind this is a large update - do not ask mod developers for ETAs.
</div>
<?php } ?>
<div class="input-group hidden-print">
    <span class="input-group-addon"><i class="fa fa-search"></i><span class="sr-only">Search</span></span>
    <input type="text" id="search" class="form-control" placeholder="Type to search" autofocus />
    <span class="input-group-btn">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Mode <span class="caret"></span></button>
        <ul class="dropdown-menu pull-right">
            <li><a id="search-simple">Simple Search</a></li>
            <li><a id="search-advanced">Advanced Search</a></li>
            <li class="divider"></li>
            <li><a id="search-reset">Reset Search Fields</a></li>
        </ul>
    </span>
</div>
<div class="input-group hidden-print advanced-search hidden-search">
    <span class="input-group-addon"><i class="fa fa-credit-card"></i><span class="sr-only">Name Search</span></span>
    <input type="text" id="search-name" class="form-control" placeholder="Mod Name" />
    <span class="input-group-addon"><i class="fa fa-group"></i><span class="sr-only">Author Search</span></span>
    <input type="text" id="search-author" class="form-control" placeholder="Author" />
    <span class="input-group-addon"><i class="fa fa-book"></i><span class="sr-only">Description Search</span></span>
    <input type="text" id="search-desc" class="form-control" placeholder="Description" />
    <span class="input-group-addon"><i class="fa fa-tags"></i><span class="sr-only">Tag Search</span></span>
    <input type="text" id="search-tag" class="form-control" placeholder="Tags" />
</div>
<table id="modlist" class="table table-hover modlist-table">
    <thead>
        <tr>
            <th>Mod Name <span class="pull-right">Author</span></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->mods as $mod) { ?>
        <tr id="<?=preg_replace("/[^0-9a-zA-Z]/i", '', strtolower($mod['name'])) ?>">
            <td>
                <p>
                    <span>
                        <a href="<?=$mod['link'] ?>" target="_blank"><?=$mod['name'] ?></a>
                        <?php
                        if (isset($mod['other'])) { echo $mod['other']; }
                        ?>
                    </span>
                    <strong>
                        <i class="pull-right"><?=implode(", ", $mod['author']) ?></i>
                    </strong>
                </p>
            <?php if (isset($mod['desc']) && $mod['desc'] !== "") { ?>
                <p><?=$mod['desc'] ?></p>
            <?php } ?>
                <p>
            <?php if (isset($mod['source'])) { ?>
                <?php if ($mod['source'] !== "") { ?>
                    <a href="<?=$mod['source'] ?>">
                        <span class="fa-stack pull-right opensource">
                            <i class="fa fa-file-o fa-stack-1x"></i>
                            <strong class="fa-stack-1x fa-stack-text file-text"></strong>
                        </span>
                        <span class="sr-only">Open Source</span>
                    </a>
                <?php } else { ?>
                    <span class="fa-stack pull-right opensource-contained">
                        <i class="fa fa-file-o fa-stack-1x"></i>
                        <strong class="fa-stack-1x fa-stack-text file-text"></strong>
                    </span>
                    <span class="sr-only">Open Source</span>
                <?php } ?>
            <?php } ?>
            <?php foreach ($mod['type'] as $type) { ?>
                <span class="label label-default <?=strtolower($type) ?>"><?=$this->type[$type] ?></span>
            <?php } ?>
            <?php foreach ($mod['dependencies'] as $dependency) { $forge_type = strtolower(str_replace(' ', '-', $dependency)); ?>
                <?php if (isset($this->forge[$forge_type])) { ?>
                    <a href="#forge" class="depends">
                        <span class="label label-<?=$this->forge[$forge_type] ?> dependency <?=$forge_type ?>"><?=$dependency ?></span>
                    </a>
                <?php } elseif ($forge_type === 'base-edit') { ?>
                    <a href="/faq#base-edit" class="depends">
                        <span class="label label-danger base-edit">Base Edit</span>
                    </a>
                <?php } else { ?>
                    <a href="#<?=strtolower(preg_replace("/[^0-9a-zA-Z]/i", '', str_replace(array(" Compatible", " Required"), "", $dependency))) ?>" class="depends">
                        <span class="label label-warning dependency"><?=$dependency ?></span>
                    </a>
                <?php } ?>
            <?php } ?>
                </p>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>